/* tslint:disable */
/* eslint-disable */
/**
 * Reservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Ambulance
 */
export interface Ambulance {
    /**
     * 
     * @type {string}
     * @memberof Ambulance
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Ambulance
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Ambulance
     */
    'address'?: string;
    /**
     * 
     * @type {OfficeHours}
     * @memberof Ambulance
     */
    'officeHours'?: OfficeHours;
    /**
     * 
     * @type {Array<MedicalExaminations>}
     * @memberof Ambulance
     */
    'medicalExaminations'?: Array<MedicalExaminations>;
}
/**
 * 
 * @export
 * @interface GetAmbulanceReservationsById200Response
 */
export interface GetAmbulanceReservationsById200Response {
    /**
     * 
     * @type {Ambulance}
     * @memberof GetAmbulanceReservationsById200Response
     */
    'ambulance'?: Ambulance;
    /**
     * 
     * @type {Array<Reservation>}
     * @memberof GetAmbulanceReservationsById200Response
     */
    'reservations'?: Array<Reservation>;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const MedicalExaminations = {
    XRay: 'X-ray',
    Mri: 'MRI',
    Ct: 'CT',
    Ultrasound: 'Ultrasound',
    BloodTest: 'Blood Test'
} as const;

export type MedicalExaminations = typeof MedicalExaminations[keyof typeof MedicalExaminations];


/**
 * 
 * @export
 * @interface OfficeHours
 */
export interface OfficeHours {
    /**
     * 
     * @type {string}
     * @memberof OfficeHours
     */
    'open'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficeHours
     */
    'close'?: string;
}
/**
 * 
 * @export
 * @interface Patient
 */
export interface Patient {
    /**
     * 
     * @type {string}
     * @memberof Patient
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Patient
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof Patient
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof Patient
     */
    'birthday': string;
    /**
     * 
     * @type {Sex}
     * @memberof Patient
     */
    'sex': Sex;
    /**
     * 
     * @type {string}
     * @memberof Patient
     */
    'bio'?: string;
}


/**
 * 
 * @export
 * @interface RequestExamination200ResponseInner
 */
export interface RequestExamination200ResponseInner {
    /**
     * 
     * @type {Ambulance}
     * @memberof RequestExamination200ResponseInner
     */
    'ambulance'?: Ambulance;
    /**
     * 
     * @type {string}
     * @memberof RequestExamination200ResponseInner
     */
    'timeSlot'?: string;
}
/**
 * 
 * @export
 * @interface RequestExaminationRequest
 */
export interface RequestExaminationRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestExaminationRequest
     */
    'date'?: string;
    /**
     * 
     * @type {MedicalExaminations}
     * @memberof RequestExaminationRequest
     */
    'examinationType'?: MedicalExaminations;
}


/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {Patient}
     * @memberof Reservation
     */
    'patient'?: Patient;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    'timeSlot'?: string;
    /**
     * Optional message for the reservation
     * @type {string}
     * @memberof Reservation
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Sex = {
    Male: 'male',
    Female: 'female'
} as const;

export type Sex = typeof Sex[keyof typeof Sex];



/**
 * AmbulanceApi - axios parameter creator
 * @export
 */
export const AmbulanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new ambulance
         * @param {Ambulance} ambulance Ambulance object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAmbulance: async (ambulance: Ambulance, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulance' is not null or undefined
            assertParamExists('createAmbulance', 'ambulance', ambulance)
            const localVarPath = `/ambulances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ambulance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes an ambulance
         * @param {string} ambulanceId ID of ambulance to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAmbulance: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('deleteAmbulance', 'ambulanceId', ambulanceId)
            const localVarPath = `/ambulances/{ambulanceId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an ambulance by ID
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulanceById: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getAmbulanceById', 'ambulanceId', ambulanceId)
            const localVarPath = `/ambulances/{ambulanceId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of all ambulances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulances: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ambulances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing ambulance
         * @param {string} ambulanceId ID of ambulance to update
         * @param {Ambulance} ambulance Ambulance object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAmbulance: async (ambulanceId: string, ambulance: Ambulance, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('updateAmbulance', 'ambulanceId', ambulanceId)
            // verify required parameter 'ambulance' is not null or undefined
            assertParamExists('updateAmbulance', 'ambulance', ambulance)
            const localVarPath = `/ambulances/{ambulanceId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ambulance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AmbulanceApi - functional programming interface
 * @export
 */
export const AmbulanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AmbulanceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new ambulance
         * @param {Ambulance} ambulance Ambulance object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAmbulance(ambulance, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes an ambulance
         * @param {string} ambulanceId ID of ambulance to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAmbulance(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get an ambulance by ID
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAmbulanceById(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Ambulance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAmbulanceById(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a list of all ambulances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAmbulances(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Ambulance>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAmbulances(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing ambulance
         * @param {string} ambulanceId ID of ambulance to update
         * @param {Ambulance} ambulance Ambulance object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAmbulance(ambulanceId: string, ambulance: Ambulance, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAmbulance(ambulanceId, ambulance, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AmbulanceApi - factory interface
 * @export
 */
export const AmbulanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AmbulanceApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new ambulance
         * @param {Ambulance} ambulance Ambulance object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAmbulance(ambulance: Ambulance, options?: any): AxiosPromise<void> {
            return localVarFp.createAmbulance(ambulance, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes an ambulance
         * @param {string} ambulanceId ID of ambulance to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAmbulance(ambulanceId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteAmbulance(ambulanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an ambulance by ID
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulanceById(ambulanceId: string, options?: any): AxiosPromise<Ambulance> {
            return localVarFp.getAmbulanceById(ambulanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of all ambulances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulances(options?: any): AxiosPromise<Array<Ambulance>> {
            return localVarFp.getAmbulances(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing ambulance
         * @param {string} ambulanceId ID of ambulance to update
         * @param {Ambulance} ambulance Ambulance object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAmbulance(ambulanceId: string, ambulance: Ambulance, options?: any): AxiosPromise<void> {
            return localVarFp.updateAmbulance(ambulanceId, ambulance, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AmbulanceApi - interface
 * @export
 * @interface AmbulanceApi
 */
export interface AmbulanceApiInterface {
    /**
     * 
     * @summary Create a new ambulance
     * @param {Ambulance} ambulance Ambulance object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApiInterface
     */
    createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Deletes an ambulance
     * @param {string} ambulanceId ID of ambulance to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApiInterface
     */
    deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get an ambulance by ID
     * @param {string} ambulanceId ID of ambulance to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApiInterface
     */
    getAmbulanceById(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<Ambulance>;

    /**
     * 
     * @summary Get a list of all ambulances
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApiInterface
     */
    getAmbulances(options?: AxiosRequestConfig): AxiosPromise<Array<Ambulance>>;

    /**
     * 
     * @summary Update an existing ambulance
     * @param {string} ambulanceId ID of ambulance to update
     * @param {Ambulance} ambulance Ambulance object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApiInterface
     */
    updateAmbulance(ambulanceId: string, ambulance: Ambulance, options?: AxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AmbulanceApi - object-oriented interface
 * @export
 * @class AmbulanceApi
 * @extends {BaseAPI}
 */
export class AmbulanceApi extends BaseAPI implements AmbulanceApiInterface {
    /**
     * 
     * @summary Create a new ambulance
     * @param {Ambulance} ambulance Ambulance object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApi
     */
    public createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig) {
        return AmbulanceApiFp(this.configuration).createAmbulance(ambulance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes an ambulance
     * @param {string} ambulanceId ID of ambulance to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApi
     */
    public deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig) {
        return AmbulanceApiFp(this.configuration).deleteAmbulance(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an ambulance by ID
     * @param {string} ambulanceId ID of ambulance to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApi
     */
    public getAmbulanceById(ambulanceId: string, options?: AxiosRequestConfig) {
        return AmbulanceApiFp(this.configuration).getAmbulanceById(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a list of all ambulances
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApi
     */
    public getAmbulances(options?: AxiosRequestConfig) {
        return AmbulanceApiFp(this.configuration).getAmbulances(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing ambulance
     * @param {string} ambulanceId ID of ambulance to update
     * @param {Ambulance} ambulance Ambulance object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceApi
     */
    public updateAmbulance(ambulanceId: string, ambulance: Ambulance, options?: AxiosRequestConfig) {
        return AmbulanceApiFp(this.configuration).updateAmbulance(ambulanceId, ambulance, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * PatientApi - axios parameter creator
 * @export
 */
export const PatientApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new patient
         * @param {Patient} patient Patient object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPatient: async (patient: Patient, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patient' is not null or undefined
            assertParamExists('createPatient', 'patient', patient)
            const localVarPath = `/patients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patient, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a patient
         * @param {string} patientId ID of patient to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePatient: async (patientId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('deletePatient', 'patientId', patientId)
            const localVarPath = `/patients/{patientId}`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a patient by ID
         * @param {string} patientId ID of patient to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatientById: async (patientId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('getPatientById', 'patientId', patientId)
            const localVarPath = `/patients/{patientId}`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get reservations for a specific patient
         * @param {string} patientId ID of patient to return reservations for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatientReservations: async (patientId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('getPatientReservations', 'patientId', patientId)
            const localVarPath = `/patients/{patientId}/reservations`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of all patients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatients: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/patients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Request an examination for a specific patient
         * @param {string} patientId ID of patient to request examination for
         * @param {RequestExaminationRequest} requestExaminationRequest Examination request details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestExamination: async (patientId: string, requestExaminationRequest: RequestExaminationRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('requestExamination', 'patientId', patientId)
            // verify required parameter 'requestExaminationRequest' is not null or undefined
            assertParamExists('requestExamination', 'requestExaminationRequest', requestExaminationRequest)
            const localVarPath = `/patients/{patientId}/request-examination`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestExaminationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing patient
         * @param {string} patientId ID of patient to update
         * @param {Patient} patient Patient object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePatient: async (patientId: string, patient: Patient, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patientId' is not null or undefined
            assertParamExists('updatePatient', 'patientId', patientId)
            // verify required parameter 'patient' is not null or undefined
            assertParamExists('updatePatient', 'patient', patient)
            const localVarPath = `/patients/{patientId}`
                .replace(`{${"patientId"}}`, encodeURIComponent(String(patientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patient, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PatientApi - functional programming interface
 * @export
 */
export const PatientApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PatientApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new patient
         * @param {Patient} patient Patient object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPatient(patient: Patient, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPatient(patient, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes a patient
         * @param {string} patientId ID of patient to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePatient(patientId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePatient(patientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a patient by ID
         * @param {string} patientId ID of patient to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPatientById(patientId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Patient>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPatientById(patientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get reservations for a specific patient
         * @param {string} patientId ID of patient to return reservations for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPatientReservations(patientId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Reservation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPatientReservations(patientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a list of all patients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPatients(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Patient>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPatients(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Request an examination for a specific patient
         * @param {string} patientId ID of patient to request examination for
         * @param {RequestExaminationRequest} requestExaminationRequest Examination request details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestExamination(patientId: string, requestExaminationRequest: RequestExaminationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RequestExamination200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestExamination(patientId, requestExaminationRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing patient
         * @param {string} patientId ID of patient to update
         * @param {Patient} patient Patient object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePatient(patientId: string, patient: Patient, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePatient(patientId, patient, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PatientApi - factory interface
 * @export
 */
export const PatientApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PatientApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new patient
         * @param {Patient} patient Patient object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPatient(patient: Patient, options?: any): AxiosPromise<void> {
            return localVarFp.createPatient(patient, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a patient
         * @param {string} patientId ID of patient to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePatient(patientId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deletePatient(patientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a patient by ID
         * @param {string} patientId ID of patient to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatientById(patientId: string, options?: any): AxiosPromise<Patient> {
            return localVarFp.getPatientById(patientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get reservations for a specific patient
         * @param {string} patientId ID of patient to return reservations for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatientReservations(patientId: string, options?: any): AxiosPromise<Array<Reservation>> {
            return localVarFp.getPatientReservations(patientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of all patients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPatients(options?: any): AxiosPromise<Array<Patient>> {
            return localVarFp.getPatients(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Request an examination for a specific patient
         * @param {string} patientId ID of patient to request examination for
         * @param {RequestExaminationRequest} requestExaminationRequest Examination request details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestExamination(patientId: string, requestExaminationRequest: RequestExaminationRequest, options?: any): AxiosPromise<Array<RequestExamination200ResponseInner>> {
            return localVarFp.requestExamination(patientId, requestExaminationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing patient
         * @param {string} patientId ID of patient to update
         * @param {Patient} patient Patient object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePatient(patientId: string, patient: Patient, options?: any): AxiosPromise<void> {
            return localVarFp.updatePatient(patientId, patient, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PatientApi - interface
 * @export
 * @interface PatientApi
 */
export interface PatientApiInterface {
    /**
     * 
     * @summary Create a new patient
     * @param {Patient} patient Patient object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    createPatient(patient: Patient, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Deletes a patient
     * @param {string} patientId ID of patient to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    deletePatient(patientId: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a patient by ID
     * @param {string} patientId ID of patient to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    getPatientById(patientId: string, options?: AxiosRequestConfig): AxiosPromise<Patient>;

    /**
     * 
     * @summary Get reservations for a specific patient
     * @param {string} patientId ID of patient to return reservations for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    getPatientReservations(patientId: string, options?: AxiosRequestConfig): AxiosPromise<Array<Reservation>>;

    /**
     * 
     * @summary Get a list of all patients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    getPatients(options?: AxiosRequestConfig): AxiosPromise<Array<Patient>>;

    /**
     * 
     * @summary Request an examination for a specific patient
     * @param {string} patientId ID of patient to request examination for
     * @param {RequestExaminationRequest} requestExaminationRequest Examination request details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    requestExamination(patientId: string, requestExaminationRequest: RequestExaminationRequest, options?: AxiosRequestConfig): AxiosPromise<Array<RequestExamination200ResponseInner>>;

    /**
     * 
     * @summary Update an existing patient
     * @param {string} patientId ID of patient to update
     * @param {Patient} patient Patient object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApiInterface
     */
    updatePatient(patientId: string, patient: Patient, options?: AxiosRequestConfig): AxiosPromise<void>;

}

/**
 * PatientApi - object-oriented interface
 * @export
 * @class PatientApi
 * @extends {BaseAPI}
 */
export class PatientApi extends BaseAPI implements PatientApiInterface {
    /**
     * 
     * @summary Create a new patient
     * @param {Patient} patient Patient object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public createPatient(patient: Patient, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).createPatient(patient, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a patient
     * @param {string} patientId ID of patient to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public deletePatient(patientId: string, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).deletePatient(patientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a patient by ID
     * @param {string} patientId ID of patient to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public getPatientById(patientId: string, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).getPatientById(patientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get reservations for a specific patient
     * @param {string} patientId ID of patient to return reservations for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public getPatientReservations(patientId: string, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).getPatientReservations(patientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a list of all patients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public getPatients(options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).getPatients(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Request an examination for a specific patient
     * @param {string} patientId ID of patient to request examination for
     * @param {RequestExaminationRequest} requestExaminationRequest Examination request details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public requestExamination(patientId: string, requestExaminationRequest: RequestExaminationRequest, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).requestExamination(patientId, requestExaminationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing patient
     * @param {string} patientId ID of patient to update
     * @param {Patient} patient Patient object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientApi
     */
    public updatePatient(patientId: string, patient: Patient, options?: AxiosRequestConfig) {
        return PatientApiFp(this.configuration).updatePatient(patientId, patient, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ReservationApi - axios parameter creator
 * @export
 */
export const ReservationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {Reservation} reservation Reservation object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservation: async (ambulanceId: string, reservation: Reservation, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('createReservation', 'ambulanceId', ambulanceId)
            // verify required parameter 'reservation' is not null or undefined
            assertParamExists('createReservation', 'reservation', reservation)
            const localVarPath = `/ambulances/{ambulanceId}/reservations`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reservation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservation: async (ambulanceId: string, reservationId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('deleteReservation', 'ambulanceId', ambulanceId)
            // verify required parameter 'reservationId' is not null or undefined
            assertParamExists('deleteReservation', 'reservationId', reservationId)
            const localVarPath = `/ambulances/{ambulanceId}/reservations/{reservationId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"reservationId"}}`, encodeURIComponent(String(reservationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an ambulance by ID along with the list of medical examination reservations
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulanceReservationsById: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getAmbulanceReservationsById', 'ambulanceId', ambulanceId)
            const localVarPath = `/ambulances/{ambulanceId}/reservations`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a reservation by ID
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationById: async (ambulanceId: string, reservationId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getReservationById', 'ambulanceId', ambulanceId)
            // verify required parameter 'reservationId' is not null or undefined
            assertParamExists('getReservationById', 'reservationId', reservationId)
            const localVarPath = `/ambulances/{ambulanceId}/reservations/{reservationId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"reservationId"}}`, encodeURIComponent(String(reservationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to update
         * @param {Reservation} reservation Reservation object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateReservation: async (ambulanceId: string, reservationId: number, reservation: Reservation, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('updateReservation', 'ambulanceId', ambulanceId)
            // verify required parameter 'reservationId' is not null or undefined
            assertParamExists('updateReservation', 'reservationId', reservationId)
            // verify required parameter 'reservation' is not null or undefined
            assertParamExists('updateReservation', 'reservation', reservation)
            const localVarPath = `/ambulances/{ambulanceId}/reservations/{reservationId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"reservationId"}}`, encodeURIComponent(String(reservationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reservation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReservationApi - functional programming interface
 * @export
 */
export const ReservationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReservationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {Reservation} reservation Reservation object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createReservation(ambulanceId: string, reservation: Reservation, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createReservation(ambulanceId, reservation, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes a reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteReservation(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteReservation(ambulanceId, reservationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get an ambulance by ID along with the list of medical examination reservations
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAmbulanceReservationsById(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAmbulanceReservationsById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAmbulanceReservationsById(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a reservation by ID
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReservationById(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Reservation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReservationById(ambulanceId, reservationId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to update
         * @param {Reservation} reservation Reservation object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateReservation(ambulanceId: string, reservationId: number, reservation: Reservation, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateReservation(ambulanceId, reservationId, reservation, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ReservationApi - factory interface
 * @export
 */
export const ReservationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReservationApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {Reservation} reservation Reservation object that needs to be added
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservation(ambulanceId: string, reservation: Reservation, options?: any): AxiosPromise<void> {
            return localVarFp.createReservation(ambulanceId, reservation, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservation(ambulanceId: string, reservationId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteReservation(ambulanceId, reservationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an ambulance by ID along with the list of medical examination reservations
         * @param {string} ambulanceId ID of ambulance to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulanceReservationsById(ambulanceId: string, options?: any): AxiosPromise<GetAmbulanceReservationsById200Response> {
            return localVarFp.getAmbulanceReservationsById(ambulanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a reservation by ID
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationById(ambulanceId: string, reservationId: number, options?: any): AxiosPromise<Reservation> {
            return localVarFp.getReservationById(ambulanceId, reservationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing reservation
         * @param {string} ambulanceId ID of ambulance for the reservation
         * @param {number} reservationId ID of reservation to update
         * @param {Reservation} reservation Reservation object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateReservation(ambulanceId: string, reservationId: number, reservation: Reservation, options?: any): AxiosPromise<void> {
            return localVarFp.updateReservation(ambulanceId, reservationId, reservation, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReservationApi - interface
 * @export
 * @interface ReservationApi
 */
export interface ReservationApiInterface {
    /**
     * 
     * @summary Create a new reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {Reservation} reservation Reservation object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApiInterface
     */
    createReservation(ambulanceId: string, reservation: Reservation, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Deletes a reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApiInterface
     */
    deleteReservation(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get an ambulance by ID along with the list of medical examination reservations
     * @param {string} ambulanceId ID of ambulance to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApiInterface
     */
    getAmbulanceReservationsById(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<GetAmbulanceReservationsById200Response>;

    /**
     * 
     * @summary Get a reservation by ID
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApiInterface
     */
    getReservationById(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig): AxiosPromise<Reservation>;

    /**
     * 
     * @summary Update an existing reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to update
     * @param {Reservation} reservation Reservation object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApiInterface
     */
    updateReservation(ambulanceId: string, reservationId: number, reservation: Reservation, options?: AxiosRequestConfig): AxiosPromise<void>;

}

/**
 * ReservationApi - object-oriented interface
 * @export
 * @class ReservationApi
 * @extends {BaseAPI}
 */
export class ReservationApi extends BaseAPI implements ReservationApiInterface {
    /**
     * 
     * @summary Create a new reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {Reservation} reservation Reservation object that needs to be added
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApi
     */
    public createReservation(ambulanceId: string, reservation: Reservation, options?: AxiosRequestConfig) {
        return ReservationApiFp(this.configuration).createReservation(ambulanceId, reservation, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApi
     */
    public deleteReservation(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig) {
        return ReservationApiFp(this.configuration).deleteReservation(ambulanceId, reservationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an ambulance by ID along with the list of medical examination reservations
     * @param {string} ambulanceId ID of ambulance to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApi
     */
    public getAmbulanceReservationsById(ambulanceId: string, options?: AxiosRequestConfig) {
        return ReservationApiFp(this.configuration).getAmbulanceReservationsById(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a reservation by ID
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApi
     */
    public getReservationById(ambulanceId: string, reservationId: number, options?: AxiosRequestConfig) {
        return ReservationApiFp(this.configuration).getReservationById(ambulanceId, reservationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing reservation
     * @param {string} ambulanceId ID of ambulance for the reservation
     * @param {number} reservationId ID of reservation to update
     * @param {Reservation} reservation Reservation object that needs to be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReservationApi
     */
    public updateReservation(ambulanceId: string, reservationId: number, reservation: Reservation, options?: AxiosRequestConfig) {
        return ReservationApiFp(this.configuration).updateReservation(ambulanceId, reservationId, reservation, options).then((request) => request(this.axios, this.basePath));
    }
}


