/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XskribaXbublavyReservationApp {
    }
}
declare global {
    interface HTMLXskribaXbublavyReservationAppElement extends Components.XskribaXbublavyReservationApp, HTMLStencilElement {
    }
    var HTMLXskribaXbublavyReservationAppElement: {
        prototype: HTMLXskribaXbublavyReservationAppElement;
        new (): HTMLXskribaXbublavyReservationAppElement;
    };
    interface HTMLElementTagNameMap {
        "xskriba-xbublavy-reservation-app": HTMLXskribaXbublavyReservationAppElement;
    }
}
declare namespace LocalJSX {
    interface XskribaXbublavyReservationApp {
    }
    interface IntrinsicElements {
        "xskriba-xbublavy-reservation-app": XskribaXbublavyReservationApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xskriba-xbublavy-reservation-app": LocalJSX.XskribaXbublavyReservationApp & JSXBase.HTMLAttributes<HTMLXskribaXbublavyReservationAppElement>;
        }
    }
}
